# Generated by Django 3.2.4 on 2021-06-29 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='slug_field',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
