# Generated by Django 3.2.4 on 2021-07-04 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20210704_2027'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newuser',
            name='is_admin',
        ),
        migrations.RemoveField(
            model_name='newuser',
            name='is_editor',
        ),
        migrations.RemoveField(
            model_name='newuser',
            name='is_viewer',
        ),
    ]
